# Generated by Django 3.2.7 on 2021-09-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('release', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=300)),
                ('chapter', models.CharField(max_length=255)),
            ],
        ),
    ]
