# Generated by Django 3.2.7 on 2021-09-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='comic_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
