# Generated by Django 3.2.7 on 2021-09-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicapi', '0002_comic_comic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='rating',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
